name: Package Application with Pyinstaller

on: [push]
permissions:
  id-token: "write"
  contents: "write"
  packages: "write"
  pull-requests: "read"

jobs:
  winbuild: # Windows build
    name: Build package on Windows
    runs-on: windows-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller "PySide6-Essentials==6.4.0.1"

    - name: Install UPX
      uses: crazy-max/ghaction-upx@v3
      with:
        install-only: true

    - name: Package application
      run: |
        pyinstaller -i icons/icon.ico -F -w --clean --log-level WARN main.py

    - name: Upload package
      uses: actions/upload-artifact@v4
      with:
        name: win
        path: dist/main.exe

  macbuild: # MacOS Build
    name: Build package on MacOS
    runs-on: macos-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller "PySide6-Essentials==6.4.0.1"
  
    - name: Package application
      run: |
        pyinstaller -i icons/icon.icns -F -w --clean --log-level WARN main.py
        cd dist
        zip -r9 checker.zip main.app/

    - name: Upload package
      uses: actions/upload-artifact@v4
      with:
        name: mac
        path: dist/checker.zip

  upload: # Upload releases
    name: Upload releases
    runs-on: ubuntu-latest
    needs: [winbuild, macbuild]

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4

    - name: Remame artifacts
      run: |
        mv win/main.exe checker-win-x64.exe
        mv mac/checker.zip checker-mac.zip

    - name: Create & upload release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: alpha
        prerelease: true
        title: GoogleTranslate_IPFinder
        files: |
          checker-win-x64.exe
          checker-mac.zip
